### PR TITLE
update to 0.12.3

### PR DESCRIPTION
**Pull request by zendre4**
Update wkhtmltopdf binary to 0.12.3

### CODE REVIEW

**Comment by h4cc** [comment]
Sorry but i cant merge binary files. Thanks for your effort!

**Comment by zendre4** [comment]
No problem, can you just tell me what is false ? (For the next time)

**Comment by h4cc** [comment]
I would have needed to compare checksums, but even these could be faked. So it was mostly a security measure.

**Comment by zendre4** [comment]
Ok no problem, thanks
Le 2 févr. 2016 21:53, "Julius Beckmann" <notifications@github.com> a
écrit :

**Pull request closed without merging**
