### PR TITLE
Update binary file to 0.12.4

### PR DESCRIPTION
**Pull request by filipegar**
Just updated the binary file to 0.12.4 (november/16 - file from http://wkhtmltopdf.org/downloads.html).

### CODE REVIEW

**Comment by filipegar** [comment]
@h4cc any news on this one?

**Comment by mitin001** [comment]
If anyone wants to use the binary from @filipegar with composer, you can list his repository in `composer.json`, and it'll use it as a proxy for the repository from @h4cc:
```
{
	"require": {
		"h4cc/wkhtmltopdf-amd64": "dev-master"
	},
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/filipegar/wkhtmltopdf-amd64"
		}
	]
}
```
Alternatively, you can use the binary from @zendre4 (discussed in #24):
```
{
	"require": {
		"zendre4/wkhtmltopdf-amd64": "0.12.4"
	}
}
```

**Comment by mhlavac** [comment]
@h4cc do you have some spare time to merge this one?

**Comment by srottem** [comment]
Bump - has this repo been abandoned?

**Comment by mhlavac** [comment]
h4cc merged something yesterday. Hopefully this gets merged as well.

**Comment by h4cc** [comment]
I updated all versions(amd64/i386/pdf/image) all at once. Thank you for your endurance with me

**Pull request closed without merging**
