### PR TITLE
Updated binary to 0.12.5

### PR DESCRIPTION
**Pull request by okdewit**
See these issues: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001

### CODE REVIEW

**Comment by Chekote** [comment]
I'm getting this error when I try to use the updated binary:

`error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory`

This is on Ubuntu 18.04. There does not seem to be a libpng12 package available:

```
$ apt-cache search libpng
libpng-dev - PNG library - development (version 1.6)
libpng-tools - PNG library - tools (version 1.6)
libpng16-16 - PNG library - runtime (version 1.6)
libpng++-dev - C++ interface to the PNG (Portable Network Graphics) library
libpng-sixlegs-java - Sixlegs Java PNG Decoder
libpng-sixlegs-java-doc - Documentation for Sixlegs Java PNG Decoder
libpnglite-dev - lightweight C library for loading and writing PNG images
libpnglite0 - lightweight C library for loading and writing PNG images
```

libpng16 is already installed:

```
$ apt-cache policy libpng16-16
libpng16-16:
  Installed: 1.6.34-1
  Candidate: 1.6.34-1
  Version table:
 *** 1.6.34-1 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by amitailanciano** [comment]
Any update on this merge? Thanks in advance!

See https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001#issuecomment-390964228

**Comment by Chekote** [comment]
FYI: I could not get this to work, so I had to abandon the composer package and install the debian package from here instead: https://builds.wkhtmltopdf.org/

**Comment by okdewit** [comment]
@Chekote This merge request is literally just the compiled 0.12.5 binary from wkhtmltopdf.org dropped in to the bin directory. For us, this resolved the SSL issues without having to downgrade & hold libssl.

I agree that it would not be a good idea to merge this without testing it on several distributions.

**Comment by maddhatter** [comment]
I've deployed this PR to resolve problems on Ubuntu 16.04.4 without any issues.

**Comment by Alexwijn** [comment]
I also run in it just fine on Ubuntu 18.4.

**Comment by adrianwaler** [comment]
When we can expect version?

**Comment by okdewit** [comment]
@adrianwaler I can imagine @h4cc doesn't want to merge this blindly without testing considering it might break many servers, but you can try whether the newer binary works for you, by temporarily adding this to your composer.json:
```json
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/TemperWorks/wkhtmltopdf-amd64"
}],
```

**Comment by nam-co** [comment]
thanks @okdewit , I tried but Im getting a The exit status code '2' says something went wrong: stderr: , is there anything else I need to do before I can use it? appreciate the help

**Comment by driesvints** [comment]
FYI: this binary is a dev version. The final 0.12.5 release was released on June 11: https://wkhtmltopdf.org/downloads.html

The Ubuntu 18.04 above from @Chekote is fixed with 0.12.5 but we'll need the Bionic release from wkhtmltopdf (wkhtmltox_0.12.5-1.bionic_amd64.deb): https://github.com/wkhtmltopdf/wkhtmltopdf/releases

**Comment by punithbm** [comment]
@h4cc  we've deployed this PR to resolve problems on Ubuntu 16.04.4 without any issues.

**Comment by rvanlaak** [comment]
@okdewit Can you also tag your `master` as `0.12.5` ? Solely adding the repository doesn't do the trick  with `"h4cc/wkhtmltopdf-amd64": "~0.12"` in our composer.json ;-)

Running `composer require "h4cc/wkhtmltopdf-amd64:dev-master"` did the trick though.

**Comment by driesvints** [comment]
@rvanlaak you can target the specific commit if you want: `"h4cc/wkhtmltopdf-amd64": "dev-master#b184b7b04aaacc6a759cc14839041c2b61f4f3cb"`

But like I said, it's still a dev version and not the final release.

**Comment by rvanlaak** [comment]
Still no luck on Platform.sh, as `libjpeg` isn't available. Was it compiled together with the binary before? Or this error occurs because this PR uses the `dev` version?

image

**Comment by driesvints** [comment]
@rvanlaak don't think that's compiled with the library. You'll need to install it yourself. Here's for Ubuntu 16.04+

```
sudo apt update -y
sudo apt install -y libjpeg libpng
```

**Comment by axzx** [comment]
@h4cc what about this?

**Comment by rvanlaak** [comment]
Would be great to get this merged. We can not use `apt` on platform, so https://github.com/h4cc/wkhtmltopdf-amd64/pull/30#issuecomment-409855944 isn't an option.

**Comment by barryvdh** [comment]
The old version had that compiled, right? Is there now way to have the compiled version? https://github.com/h4cc/wkhtmltopdf-amd64/pull/35 from @silasrm also doesn't have those binaries bundled.

**Comment by silasrm** [comment]
@h4cc show me how I bundle these binaries?

**Comment by Shardj** [comment]
@okdewit you should create a tag for the 0.12.5 binary in that repo

**Comment by rbrisita** [comment]
This hasn't been updated eight months later so anyone finding this and using PHP composer can edit composer.json to have:

```json
   "repositories": [{
        "type": "vcs",
        "url": "https://github.com/TemperWorks/wkhtmltopdf-amd64"
    }],
    "require": {
        "h4cc/wkhtmltopdf-amd64": "dev-master#b184b7b",
    },
```

Then on the host machine run:

1. `sudo apt-get install -y libjpeg-dev`
1.  `composer update h4cc/wkhtmltopdf-amd64` or `composer install`

Another approach is to modify the configuration of the package you are using and make it point to the OS installed tools, which would be version 0.12.5+. For instance the Laravel Snappy library has a `config\snappy.php` file that has:

`'binary'  => 'xvfb-run wkhtmltopdf',`

**Comment by BorislavSabev** [comment]
Hello, any idea if this will come out? Can we help with something so it is not blocked anymore.

**Comment by benr77** [comment]
Sigh..........

This issue has been ongoing for so long and @h4cc does not seem to be maintaining this repo any longer. I believe the build process is not published anywhere, for anyone to take over.

@rbrisita thank you for your extremely useful details about pointing composer at the TemperWorks repo. 

Please could you or @okdewit tell me if this is the 0.12.5 beta binary or the final release in the TemperWorks repo?

**Comment by kiwdahc** [comment]
Same as above, I am going to use the TemperWorks repo but don't consider this a permanent solution. I would be willing to help implement one.

**Comment by Shardj** [comment]
Pretty frustrating situation, we've gone with docker builds installing wkhtml instead of using composer, this gets around this issue. Felt like a more sustainable solution when compared to the lack of progress on this by @h4cc as we can only assume he's abandoned this without passing it on.

**Comment by okdewit** [comment]
>Please could you or @okdewit tell me if this is the 0.12.5 beta binary or the final release in the TemperWorks repo?

I'm pretty sure only the (debian) beta was out when I made this fork.

We're moving on to other solutions, this was just a quick hotfix. I personally don't have the time/resources to maintain a composer wrapped package of the wkhtmltopdf binary, as it comes with the responsibility of testing it on many server distributions. 

You can keep using this branch, but I'd advise anyone to just download their binaries straight from https://wkhtmltopdf.org/downloads.html, **pick the version which is appropriate for your server**, because there are actually differences between the distribution builds. You could commit the binary straight to your codebase (and add it to path), install it directly on your server, or create a docker container.

If you really want a composer package, you can of course also just fork the @h4cc repo and copy in the binary that works for you.

**Comment by rbrisita** [comment]
Thanks for following up @okdewit and thank you for your efforts and transparency. With what is now known, it would be appreciated if @h4cc marked this project as abandoned to alert others in the future.

I would suggest to not follow instructions to have ['wkhtmltopdf binary as composer dependencies'](https://github.com/KnpLabs/snappy#wkhtmltopdf-binary-as-composer-dependencies) but to have the binaries as OS level tools under [Composer's `scripts` section](https://getcomposer.org/doc/articles/scripts.md). Binaries can be found [here](https://wkhtmltopdf.org/downloads.html) and take note that under Linux systems the tools also have dependencies of:

- xvfb
- libxrender1
- libfontconfig1

Which ever [integration](https://github.com/KnpLabs/snappy#snappy) you use for Snappy make sure it is configured to use the OS level tools as I mentioned in my [previous post](https://github.com/h4cc/wkhtmltopdf-amd64/pull/30#issuecomment-448611958). Keeping it in Composer keeps everything organized in regard to the project, which is one of the reasons for this repository.

**Comment by Shardj** [comment]
@rbrisita all of the download links I see on the official page are distro specific packages not binaries. Unless I have a fundamental misunderstanding which is possible.

@okdewit thanks for providing an answer

**Comment by okdewit** [comment]
> @rbrisita all of the download links I see on the official page are distro specific packages not binaries. Unless I have a fundamental misunderstanding which is possible.

@Shardj: If you use a less common Linux server distribution, you could unpack a distro specific package with most archival tools and extract the binary & libraries, and try to manually figure out what should go where on your server. A deb or rpm is like a zip file, with a folder structure in it, with some checksum metadata. Because distributions can have slightly different directory structures and different dynamic libraries/versions, it might or might not work if you manually hack it in, and from a devops perspective it's not really recommended.

The h4cc package is just that -- an extracted binary wrapped in a composer package, which kind of assumes that all required libraries are already present on your server. If your server happens to be a more uncommon system (for example, a Raspberry Pi with an ARM chip), the binary shipped in the composer package would fail to run.

If you use a common server distro like Ubuntu or CentOS, you could use the composer scripts section, retrieve the pre-built package of your choice with curl/wget, and use the OS package manager to install it as intended.

If you use an uncommon server distro/architecture and there is no pre-built package, and using the unzipped binary from the deb/rpm fails as well, you'd have to compile it for your system.

**Comment by Shardj** [comment]
@okdewit thanks that's very helpful!

**Comment by ao5357** [comment]
If anyone else is using platform.sh and wants the stable 0.12.5 rather than the dev from TemperWorks, you can use https://github.com/ao5357/wkhtmltopdf-amd64 (I may not maintain it, cannot vouch for its universal compatibility, etc. But I will keep it as a live repo for composer builds). It resolved my immediate issue.

`
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/ao5357/wkhtmltopdf-amd64"
    }
  ]
`
and
`
"require": {
  "h4cc/wkhtmltopdf-amd64": "dev-master#c216cb8dc9b1323"
}
`

**Comment by Varin6** [comment]
Hi everyone, 
I also had an issue with the libpng12 and libjpeg62 that @Chekote mentioned above on Ubuntu 18.04. I have managed to fix it this way:

1. `sudo apt-get install libjpeg62` - this installed the first missing library
2. With the second one, libpng12 I had more issues as it's not available via apt-get any more but I've found a solution somewhere on StackOverflow. All I had to do was to run this command:
```
wget -q -O /tmp/libpng12.deb http://mirrors.kernel.org/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb \
  && dpkg -i /tmp/libpng12.deb \
  && rm /tmp/libpng12.deb
```
This is from this topic: https://askubuntu.com/questions/978294/how-to-fix-libpng12-so-0-cannot-open-shared-object-file-no-such-file-or-direc

After those two fixes, it worked. Hope this helps someone

**Comment by andersonefecto** [comment]
> dev-master#c216cb8dc9b1323

Thanks! That was the only thing that worked for me.

Updating the composer.json of Laravel to:

`"h4cc/wkhtmltopdf-amd64": "dev-master#c216cb8dc9b1323",`

**Comment by eliurkis** [comment]
> If anyone else is using platform.sh and wants the stable 0.12.5 rather than the dev from TemperWorks, you can use https://github.com/ao5357/wkhtmltopdf-amd64 (I may not maintain it, cannot vouch for its universal compatibility, etc. But I will keep it as a live repo for composer builds). It resolved my immediate issue.
> 
> `"repositories": [ { "type": "vcs", "url": "https://github.com/ao5357/wkhtmltopdf-amd64" } ]`
> and
> `"require": { "h4cc/wkhtmltopdf-amd64": "dev-master#c216cb8dc9b1323" }`

Worked like a charm for me! Other versions were causing `SSL` issues for me

**Pull request closed without merging**
